import type { Metadata } from "next";
import { Anton_SC, Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/sections/footer";
import Navigation from "@/sections/navigation";

const anton = Anton_SC({
  weight: "400",
  variable: "--font-anton",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anton.variable} ${inter.variable} antialiased font-inter select-none`}
      >
        <Navigation />
        <main className=" min-h-screen">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
